version: '3.5'
services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: returnnull_nginx
    volumes:
      - ./code/public:/var/www/html/public
    ports:
      - '80:80'

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: returnnull_php_fpm
    volumes:
      - ./code:/var/www/html

  database:
    build:
      context: docker/database
      dockerfile: Dockerfile
    container_name: returnnull_mysql
    volumes:
      - ./database:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=blog
    ports:
      - '3306:3306'

  sass:
    build:
      context: docker/sass
      dockerfile: Dockerfile
    container_name: returnnull_sass
    volumes:
      - ./code/public/css:/var/www/html